#!/usr/bin/perl
#	$tagram.loom: smtpd.pl,v 1.0 2026/04/13 doom Exp $

# Copyright (c) 2026 doom <doom@tagram.loom>
# Based on relayd.pl by Alexander Bluhm <bluhm@openbsd.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;
use Socket;

use Client;
use Smtpd;
use Lmtp;
require 'funcs.pl';

sub usage {
	die "usage: smtpd.pl [test-args.pl]\n";
}

my $testfile;
our %args;
if (@ARGV and -f $ARGV[-1]) {
	$testfile = pop;
	do $testfile
	    or die "Do test file $testfile failed: ", $@ || $!;
}
@ARGV == 0 or usage();

# Allocate two ports up front: one for smtpd to listen on (SMTP client
# connects here), one for the LMTP sink to listen on (smtpd delivers here).
my ($smtp_port, $lmtp_port) = find_ports(num => 2);

my ($c, $d, $s);

# LMTP sink — must bind before smtpd reads its config.
$s = Lmtp->new(
    forward      => "smtp",
    func         => \&lmtp_server,
    listendomain => AF_INET,
    listenaddr   => "127.0.0.1",
    listenport   => $lmtp_port,
    %{$args{server} || {}},
    testfile     => $testfile,
) unless ($args{server} || {})->{noserver};

# smtpd under test — config generated by Smtpd.pm from args{smtpd}{config}.
$d = Smtpd->new(
    listenaddr   => "127.0.0.1",
    listenport   => $smtp_port,
    connectaddr  => "127.0.0.1",
    connectport  => $lmtp_port,
    %{$args{smtpd} || {}},
    testfile     => $testfile,
);

# SMTP client — connects to smtpd's listen port.
$c = Client->new(
    forward       => "smtp",
    func          => \&smtp_client,
    connectdomain => AF_INET,
    connectaddr   => "127.0.0.1",
    connectport   => $smtp_port,
    %{$args{client} || {}},
    testfile      => $testfile,
    server        => \$s,
) unless ($args{client} || {})->{noclient};

# Start LMTP sink first so smtpd can connect at delivery time.
$s->run unless ($args{server} || {})->{noserver};

# Start smtpd and wait for it to announce itself ready.
$d->run;
$d->up;

# Start SMTP client and wait for it to report "Connected".
$c->run->up unless ($args{client} || {})->{noclient};

# Wait for LMTP sink to accept a connection (delivery).
$s->up unless ($args{server} || {})->{noserver};

# Wait for client and LMTP sink to finish their conversations.
$c->down unless ($args{client} || {})->{noclient};
$s->down unless ($args{server} || {})->{noserver};

# Shut smtpd down cleanly.
$d->kill_child;
$d->down;

check_logs($c, $d, $s, %args);
