#	$OpenBSD$

.include <bsd.own.mk>

SUBDIR = makemap smtpd smtpctl filters
SUBDIR+=	table-ldap
#SUBDIR+=	table-mysql
SUBDIR+=	table-passwd
#SUBDIR+=	table-postgres
SUBDIR+=	table-sqlite
SUBDIR+=	table-stub

.include <bsd.subdir.mk>
