#	$OpenBSD$

.include <bsd.own.mk>

SUBDIR =	smtpd smtpctl
SUBDIR+=	makemap
SUBDIR+=	filters
SUBDIR+=	table-ldap
#SUBDIR+=	table-mysql
SUBDIR+=	table-passwd
#SUBDIR+=	table-postgres
SUBDIR+=	table-sqlite
SUBDIR+=	table-stub
#SUBDIR+=	table-redis

.include <bsd.subdir.mk>
