.\"	$OpenBSD: smtpd.conf.5,v 1.105 2013/08/08 07:08:34 jmc Exp $
.\"
.\" Copyright (c) 2013 Eric Faurot <eric@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\"
.Dd $Mdocdate: October 2 2013 $
.Dt TABLE 5
.Os
.Sh NAME
.Nm table
.Nd format description for smtpd tables
.Sh DESCRIPTION
This manual page documents the file format for the various tables used in the
.Xr smtpd 8
mail daemon.
.Pp
The format described here applies to table of type
.Ql file
as defined in
.Xr smtpd.conf 5 .
It also allows to create
.Xr db 3
databases using
.Xr makemap 8 .
.Sh TABLE TYPES
There are two types of tables: lists and mappings.
.Ss Alias tables
Bla bla
.Ss Domain tables
Bla bla
.Ss Credentials tables
Bla bla
.Ss Netaddr tables
Bla bla
.Ss Userinfo
Bla bla
.Ss Source tables
Bla bla
.Ss Mailaddr tables
Bla bla
.Ss Addrname tables
Bla bla
.Sh SEE ALSO
.Xr smtpd.conf 5
.Xr makemap 8 ,
.Xr smtpd 8
