.\"	$OpenBSD: table_passwd.5,v 1.2 2014/02/04 17:47:02 jmc Exp $
.\"
.\" Copyright (c) 2014 Gilles Chehade <gilles@poolp.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\"
.Dd $Mdocdate: February 4 2014 $
.Dt TABLE_SOCKETMAP 5
.Os
.Sh NAME
.Nm table_socketmap
.Nd format description for smtpd socketmap tables
.Sh DESCRIPTION
This manual page documents the file format of "socketmap" tables used by the
.Xr smtpd 8
mail daemon.
.Pp
The format described here applies to tables as defined in
.Xr smtpd.conf 5 .
.Sh SOCKETMAP TABLE
A "socketmap" table uses a simple protocol.
The client sends a single-line request and the server sends a single-line reply.
.Pp
The table may be used for any kind of key-based lookup and replies are expected
to follow the formats described in
.Xr table 5 .
.Sh SEE ALSO
.Xr table 5 ,
.Xr smtpd.conf 5 ,
.Xr smtpctl 8 ,
.Xr smtpd 8
