.\"	$OpenBSD: smtpd.conf.5,v 1.105 2013/08/08 07:08:34 jmc Exp $
.\"
.\" Copyright (c) 2013 Eric Faurot <eric@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\"
.Dd $Mdocdate: October 2 2013 $
.Dt TABLE 5
.Os
.Sh NAME
.Nm table
.Nd format description for smtpd tables
.Sh DESCRIPTION
This manual page documents the file format for the various tables used in the
.Xr smtpd 8
mail daemon.
.Pp
The format described here applies to tables as defined in
.Xr smtpd.conf 5 .
.Sh TABLE TYPES
There are two types of tables: lists and mappings.
A list consists of a serie of values while a mapping consists of a serie
of keys and their associated values.
The following illustrates how to declare them as static tables:
.Bd -literal -offset indent
table mylist { value1, value2, value3 }
table mymapping { key1 = value1, key2 = value2, key3 = value3 }
.Ed
.Pp
When using a
.Ql file
table, a list will be written with each value on a line by itself:
.Bd -literal -offset indent
value1
value2
value3
.Ed
.Pp
A mapping will be written with each key and value on a line,
whitespaces separating both columns:
.Bd -literal -offset indent
key1	value1
key2	value2
key3	value3
.Ed
.Pp
A file table can be converted to a
.Xr db 3
databases using the
.Xr makemap 8
utility with no syntax change.
.Pp
Tables using a
.Ql file
or
.Xr db 3
backend will be referenced as follows:
.Bd -literal -offset indent
table name file:/path/to/file
table name db:/path/to/file.db
.Ed
.Ss Aliasing tables
Aliasing tables are mappings that associate a recipient to one or many destinations.
They can be used in two contexts: primary domain aliases and virtual domain mapping.
.Pp
.Bd -literal -offset indent
accept for domain example.org alias <myaliases> deliver to mbox
accept for domain example.org virtual <myaliases> deliver to mbox
.Ed
.Pp
In a primary domain context, the key is the user-part of the recipient address,
the value is one or many recipients as described in
.Xr aliases 5 :
.Bd -literal -offset indent
user1	otheruser
user2	otheruser1,otheruser2
user3	otheruser@example.com
.Ed
.Pp
In a virtual domain context, the key is either a user-part, a full email address or
a catch all, following selection rules described in
.Xr smtpd.conf 5 ,
and the value is one or many recipients as described in
.Xr aliases 5 :
.Bd -literal -offset indent
user1			otheruser
user2@example.org	otheruser1,otheruser2
@example.org		otheruser@example.com
@			example.com
.Ed
.Ss Domain tables
Domain tables are simple lists of domains.
They can only be used in one context:
.Pp
.Bd -literal -offset indent
accept for domain <mydomains> deliver to mbox
.Ed
.Pp
In that context, the list of domains will be matched against the recipient domain.
For
.Ql static ,
.Ql file
and
.Xr db 3
backends, a wildcard may be used so the domain table may contain:
.Bd -literal -offset indent
example.org
*.example.org
.Ed
.Ss Credentials tables
Credentials tables are mappings of credentials.
They can be used in two contexts:
.Pp
.Bd -literal -offset indent
listen on tls [...] auth <credentials>
accept for any relay tls+auth://label@host auth <credentials>
.Ed
.Pp
In a listener context, the credentials are a mapping of username and encrypted passwords:
.Bd -literal -offset indent
user1	$2a$06$hIJ4QfMcp.90nJwKqGbKM.MybArjHOTpEtoTV.DgLYAiThuoYmTSe
user2	$2a$06$bwSmUOBGcZGamIfRuXGTvuTo3VLbPG9k5yeKNMBtULBhksV5KdGsK
.Ed
.Pp
The passwords are encrypted using the
.Xr crypt 3
function provided by the host.
On OpenBSD, the
.Xr encrypt 1
utility may be used, on other systems the
.Ql mkpasswd
utility is the most common method for obtaining a proper password.
.Pp
In a relay context, the credentials are a mapping of labels and username:password pairs,
where the username may be omitted if identical to the label:
.Bd -literal -offset indent
label1	user:password
label2	password
.Ed
.Pp
The label must be unique and is used as a selector for the proper credentials
when multiple credentials are valid for a single destination. The password is
not encrypted as it must be provided to the remote host.
.Ss Netaddr tables
Netaddr tables are lists of network addresses.
They can be used in two contexts:
.Pp
.Bd -literal -offset indent
accept from source <netaddr> for domain example.org deliver to mbox
accept for domain example.org relay source <netaddr>
.Ed
.Pp
When used as a "from source", the address of a client is compared to the list
of addresses in the table until a match is found.
.Pp
When used as a "relay source", the table will contain a list of IP addresses that can
be used as a source address when relaying. The IP addresses are used in sequence.
.Pp
A netaddr table looks as follow:
.Bd -literal -offset indent
192.168.1.1
::1
ipv6:::1
192.168.1.0/24
.Ed
.Ss Userinfo
Bla bla
.Ss Source tables
Bla bla
.Ss Mailaddr tables
Bla bla
.Ss Addrname tables
Bla bla
.Sh SEE ALSO
.Xr smtpd.conf 5
.Xr makemap 8 ,
.Xr smtpd 8
