SUBDIR+=	backend-queue-null
SUBDIR+=	backend-queue-ram
SUBDIR+=	backend-queue-stub
SUBDIR+=	backend-table-ldap
SUBDIR+=	backend-table-mysql
SUBDIR+=	backend-table-postgres
SUBDIR+=	backend-table-sqlite
SUBDIR+=	backend-table-stub

.include <bsd.subdir.mk>
