name: Alpine Linux (amd64 musl openssl)
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Alpine Linux (amd64 musl openssl)
      run: docker build . --file ci/docker/Dockerfile.alpine --tag notopensmtpd:alpine
