name: Archlinux (amd64 glibc libressl)
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Archlinux (amd64 glibc libressl)
      run: docker build . --file ci/docker/Dockerfile.archlinux --tag notopensmtpd:archlinux
