name: Ubuntu (amd64 glibc openssl)
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Ubuntu (amd64 glibc openssl)
      run: docker build . --file ci/docker/Dockerfile.ubuntu --tag notopensmtpd:ubuntu
